# Generated by Django 3.2.2 on 2021-06-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jampy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
